<?php
/**
 * @author  Vladan Kuzmanovic (vladankuzmanovic@gmail.com)
 */
?>

<div id="product-questions-container">
    <?php  $questionCollection = $block->getQuestionCollection(); ?>
    <!--    <h2><?php /* @escapeNotVerified */ echo __('Frequently Asked Questions') ?> </h2> -->
    <?php if(!empty($questionCollection)):?>
        <?php foreach($questionCollection as $q): ?>
            <h3><?php echo $q['nickname']; ?> asked:</h3>
            <div style="margin-top:10px;"><span style="color:#FF5252;"><strong><?php /* @escapeNotVerified */ echo __('Q:')?></strong></span><div style="margin-top:-17px; margin-left:35px;"><?php echo $q['question']; ?></div></div>
            <div style="margin-top:20px;"><span style="color:#388E3C;"><strong><?php /* @escapeNotVerified */ echo __('A:')?></strong></span><div style="margin-top:-17px; margin-left:35px;"><?php echo $q['answer']; ?></div></div>
            <hr/>
       <?php endforeach; ?>
   <?php endif; ?>
</div>
<?php echo $block->getChildHtml('question_form'); ?>
